---
Resources:

  SSHFromAnywhereSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !ImportValue vpc-stack:MyVPC
      GroupDescription: Allow SIP from anywhere
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort : 22
          ToPort : 22
          CidrIp: 0.0.0.0/0

  OpenSipsGoldenInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0d0eaed20348a3389
      InstanceType: t2.micro
      SubnetId: !ImportValue vpc-stack:PublicSubnet1
      KeyName: 2020key
      SecurityGroupIds:
        - !Ref SSHFromAnywhereSG
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash -xe
            apt-get update -y
            apt-get -y install python-pip
            apt-get -y install build-essential
            wget https://s3.amazonaws.com/amazoncloudwatch-agent/ubuntu/amd64/latest/amazon-cloudwatch-agent.deb
            dpkg -i -E amazon-cloudwatch-agent.deb

