---
Resources:
  VoipVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.1.0.0/16
      EnableDnsHostnames: true
      InstanceTenancy: default

  PubIGW:
    Type: AWS::EC2::InternetGateway

  IGWAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VoipVPC
      InternetGatewayId: !Ref PubIGW

  PubRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PubRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref PubIGW

  PubRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VoipVPC


  PubSubnetARouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PubRouteTable
      SubnetId: !Ref PublicSubnetA

  PubSubnetBRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PubRouteTable
      SubnetId: !Ref PublicSubnetB



  PublicSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: ca-central-1a
      CidrBlock: 10.1.0.0/24
      MapPublicIpOnLaunch: true
      VpcId: !Ref VoipVPC

  PublicSubnetB:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: ca-central-1b
      CidrBlock: 10.1.1.0/24
      MapPublicIpOnLaunch: true
      VpcId: !Ref VoipVPC

  PrivateSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: ca-central-1a
      CidrBlock: 10.1.2.0/24
      MapPublicIpOnLaunch: false
      VpcId: !Ref VoipVPC

  PrivateSubnetB:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: ca-central-1b
      CidrBlock: 10.1.3.0/24
      MapPublicIpOnLaunch: false
      VpcId: !Ref VoipVPC


  SipSignalingFromAnywhereSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VoipVPC
      GroupDescription: Allow SIP from anywhere
      SecurityGroupIngress:
        - IpProtocol: udp
          FromPort : 5060
          ToPort : 5060
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: udp
          FromPort : 5060
          ToPort : 5060
          CidrIp: 0.0.0.0/0

  SSHFromAnywhereSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VoipVPC
      GroupDescription: Allow SIP from anywhere
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort : 22
          ToPort : 22
          CidrIp: 0.0.0.0/0


  OpenSipsGoldenInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0d0eaed20348a3389
      InstanceType: t2.micro
      SubnetId: !Ref PublicSubnetA
      KeyName: 2020key
      SecurityGroupIds:
        - !Ref SipSignalingFromAnywhereSG
        - !Ref SSHFromAnywhereSG
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash -xe
            apt-get update -y
            apt-get -y install python-pip
            pip install https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-latest.tar.gz
            /usr/local/bin/cfn-init -s ${AWS::StackId} -r OpenSipsGoldenInstance --region ca-central-1 -c install-opensips-config-set

    Metadata:
      AWS::CloudFormation::Init:
        configSets:
          install-opensips-config-set:
            - "prereq"
            - "compile_opensips"
            - "install_opensips"
            - "start_opensips"
            - "download_cloudwatch_agent"
            - "install_cloudwatch_agent"

        prereq:
          packages:
            apt:
              build-essential: []
              flex: []
              bison: []
              libxml2-dev: []
              libmemcached-dev: []
              libssl-dev: []
              libhiredis-dev: []
              libcurl4-gnutls-dev: []
              uuid-dev: []
              liblua5.1-0-dev: []
              libmysqlclient-dev: []
              libmicrohttpd-dev: []
              libjson-c-dev: []
              libconfuse-dev: []
              libmongoc-dev: []
              ncurses-dev: []

          sources: 
            /usr/src: "https://opensips.org/pub/opensips/2.4.6/opensips-2.4.6.tar.gz"

        compile_opensips:
          commands:
            compile:
              command: "make all exclude_modules='xcap ldap proto_sctp mmgeoip db_http aaa_radius cgrates snmpstats db_oracle db_berkeley osp db_postgres h350 perl db_sqlite rabbitmq db_perlvdb event_rabbitmq cachedb_couchbase cachedb_cassandra sngtc db_unixodbc'"
              cwd: "/usr/src/opensips-2.4.6"

        install_opensips:
          commands:
            install:
              command: "make install exclude_modules='xcap ldap proto_sctp mmgeoip db_http aaa_radius cgrates snmpstats db_oracle db_berkeley osp db_postgres h350 perl db_sqlite rabbitmq db_perlvdb event_rabbitmq cachedb_couchbase cachedb_cassandra sngtc db_unixodbc'"
              cwd: "/usr/src/opensips-2.4.6"

        start_opensips:
          commands:
            start:
              command: "/usr/local/sbin/opensipsctl start"

        download_cloudwatch_agent:
          commands:
            download:
              command: "wget https://s3.amazonaws.com/amazoncloudwatch-agent/ubuntu/amd64/latest/amazon-cloudwatch-agent.deb"
              cwd: "/tmp"

        install_cloudwatch_agent:
          commands:
            install:
              command: "dpkg -i -E ./amazon-cloudwatch-agent.deb"
              cwd: "/tmp"


