---
Parameters:
  VoipVPCParameter:
    Description: Select existing VPC
    Type: AWS::EC2::VPC::Id

Resources:

  PubIGW:
    Type: AWS::EC2::InternetGateway

  IGWAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VoipVPCParameter
      InternetGatewayId: !Ref PubIGW

  PubRoute:
    Type: AWS::EC2::Route
    DependsOn:
      - PubIGW
      - IGWAttachment
    Properties:
      RouteTableId: !Ref PubRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref PubIGW

  PubRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VoipVPCParameter


  PubSubnetARouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PubRouteTable
      SubnetId: !Ref PublicSubnetA

  PubSubnetBRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PubRouteTable
      SubnetId: !Ref PublicSubnetB



  PublicSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: ca-central-1a
      CidrBlock: 10.2.0.0/24
      MapPublicIpOnLaunch: true
      VpcId: !Ref VoipVPCParameter

  PublicSubnetB:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: ca-central-1b
      CidrBlock: 10.2.1.0/24
      MapPublicIpOnLaunch: true
      VpcId: !Ref VoipVPCParameter

  PrivateSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: ca-central-1a
      CidrBlock: 10.2.2.0/24
      MapPublicIpOnLaunch: false
      VpcId: !Ref VoipVPCParameter

  PrivateSubnetB:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: ca-central-1b
      CidrBlock: 10.2.3.0/24
      MapPublicIpOnLaunch: false
      VpcId: !Ref VoipVPCParameter


  SipSignalingFromAnywhereSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VoipVPCParameter
      GroupDescription: Allow SIP from anywhere
      SecurityGroupIngress:
        - IpProtocol: udp
          FromPort : 5060
          ToPort : 5060
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: udp
          FromPort : 5060
          ToPort : 5060
          CidrIp: 0.0.0.0/0

  SSHFromAnywhereSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VoipVPCParameter
      GroupDescription: Allow SIP from anywhere
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort : 22
          ToPort : 22
          CidrIp: 0.0.0.0/0

  SIPRegistrarDNSRecordset:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: Z2ZYCU8574UYOA
      Name: registrar.sip.dpaquette.net.
      Type: A
      TTL: 300
      ResourceRecords:
        - !GetAtt OpenSipsInstance.PublicIp

  OpenSipsInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-03f645d82b117c309
      InstanceType: t2.micro
      SubnetId: !Ref PublicSubnetA
      KeyName: 2020key
      SecurityGroupIds:
        - !Ref SipSignalingFromAnywhereSG
        - !Ref SSHFromAnywhereSG
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash -xe
            apt-get update -y
            apt-get -y install python-pip
            pip install https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-latest.tar.gz
            /usr/local/bin/cfn-init -s ${AWS::StackId} -r OpenSipsInstance --region ca-central-1 -c configure-opensips-config-set

    Metadata:
      AWS::CloudFormation::Init:
        configSets:
          configure-opensips-config-set:
            - "start_opensips"

        start_opensips:
          commands:
            start:
              command: "/usr/local/sbin/opensipsctl start"


