---

- name: Configure OpenSIPS as a public registrar
  hosts: all
  become: yes
  vars_files: ./vars.yml
  vars:
    - public_ip: 15.222.13.128
    - private_ip: 10.1.1.93
  tasks:
    - name: Apply OpenSIPS template configuration file
      template:
        src: opensips-template.cfg 
        dest: /usr/local/etc/opensips/opensips.cfg


