---

- name: Configure OpenSIPS as a public registrar
  hosts: all
  become: yes
  vars_files: ./vars.yml
  tasks:
    - name: register public_ip variable
      command: "curl http://169.254.169.254/latest/meta-data/public-ipv4"
      register: public_ip

    - name: register private_ip variable
      command: "curl http://169.254.169.254/latest/meta-data/local-ipv4"
      register: private_ip

    - name: Apply OpenSIPS template configuration file
      template:
        src: opensips-template.cfg 
        dest: /usr/local/etc/opensips/opensips.cfg


