---

- name: Configure OpenSIPS as a public registrar
  hosts: all
  become: yes
  vars:
    - dbhost: voip.cluster-cspiusdu7opc.ca-central-1.rds.amazonaws.com
    - dbname: opensips
    - dbusername: opensips
    - dbpassword: blablabla

  tasks:
    - name: register public_ip variable
      command: "curl http://169.254.169.254/latest/meta-data/public-ipv4"
      register: public_ip

    - set_fact:
        public_ip = "{{ pubic_ip.stdout }}"

    - name: register private_ip variable
      command: "curl http://169.254.169.254/latest/meta-data/local-ipv4"
      register: private_ip

    - set_fact:
        private_ip = "{{ private_ip.stdout }}"

    - name: Apply OpenSIPS template configuration file
      template:
        src: opensips-template.cfg 
        dest: /usr/local/etc/opensips/opensips.cfg


