---
Resources:
  AutomationServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - ssm.amazonaws.com
            - ec2.amazonaws.com
          Action: sts:AssumeRole
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AmazonSSMAutomationRole
      - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      - arn:aws:iam::aws:policy/CloudWatchFullAccess
      Path: "/"
      RoleName: AutomationServiceRole

  SSHFromAnywhereSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !ImportValue vpc-stack:MyVPC
      GroupDescription: Allow SIP from anywhere
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort : 22
          ToPort : 22
          CidrIp: 0.0.0.0/0

  SipRegistrarSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !ImportValue vpc-stack:MyVPC
      GroupDescription: Allow SIP from anywhere
      SecurityGroupIngress:
        - IpProtocol: udp
          FromPort : 5060
          ToPort : 5060
          CidrIp: 0.0.0.0/0

  MediaServerSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !ImportValue vpc-stack:MyVPC
      GroupDescription: Allow SIP from registrar, rtp from media gateway
      SecurityGroupIngress:
        - IpProtocol: udp
          FromPort : 5060
          ToPort : 5060
          SourceSecurityGroupId: !Ref SipRegistrarSG
        - IpProtocol: udp
          FromPort : 10000
          ToPort : 30000
          SourceSecurityGroupId: !Ref RTPGatewaySG

  RTPGatewaySG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !ImportValue vpc-stack:MyVPC
      GroupDescription: Allow RTP from anywhere
      SecurityGroupIngress:
        - IpProtocol: udp
          FromPort : 10000
          ToPort : 30000
          CidrIp: 0.0.0.0/0
        - IpProtocol: udp
          FromPort : 10000
          ToPort : 30000
          SourceSecurityGroupId: !Ref MediaServerSG


Outputs:
  AutomationServiceRole:
    Description: AutomationServiceRole
    Value: !Ref AutomationServiceRole
    Export:
      Name: !Join [ ":", [ !Ref "AWS::StackName", AutomationServiceRole ] ]

  SSHFromAnywhereSG:
    Description: SSH from anywhere
    Value: !Ref SSHFromAnywhereSG
    Export:
      Name: !Join [ ":", [ !Ref "AWS::StackName", SSHFromAnywhereSG ] ]

  SipRegistrarSG:
    Description: Registrar Security Group
    Value: !Ref SipRegistrarSG
    Export:
      Name: !Join [ ":", [ !Ref "AWS::StackName", SipRegistrarSG ] ]

  MediaServerSG:
    Description: Media Server Security Group
    Value: !Ref MediaServerSG
    Export:
      Name: !Join [ ":", [ !Ref "AWS::StackName", MediaServerSG ] ]

  RTPGatewaySG:
    Description: RTP Gateway Security Group
    Value: !Ref RTPGatewaySG
    Export:
      Name: !Join [ ":", [ !Ref "AWS::StackName", RTPGatewaySG ] ]
      #      Name: "security-stack:RTPGatewaySG"


